package widgets;
import java.awt.Toolkit;

/**
 *
 * @author Nolan Ritchey
 */
public class widgets extends javax.swing.JDialog{
 
    int setX,setY;
    launcher launch = new launcher();
    int width = (Toolkit.getDefaultToolkit().getScreenSize().width/2)-325;
    /**
     * Creates new form widgets
     */
    public widgets(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(width,20);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LI = new javax.swing.JLabel();
        GM = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(350, 175));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widgets/linked.png"))); // NOI18N
        LI.setText("LI");
        LI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LI.setPreferredSize(new java.awt.Dimension(150, 150));
        LI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LIMouseClicked(evt);
            }
        });
        add(LI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        GM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/widgets/goog.png"))); // NOI18N
        GM.setText("GM");
        GM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GM.setPreferredSize(new java.awt.Dimension(150, 150));
        GM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GMMouseClicked(evt);
            }
        });
        add(GM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        back.setBackground(new java.awt.Color(0, 0, 102));
        back.setForeground(new java.awt.Color(0, 0, 102));
        back.setText("back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setOpaque(true);
        back.setPreferredSize(new java.awt.Dimension(350, 175));
        back.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backMouseDragged(evt);
            }
        });
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        setX = evt.getX();
        setY = evt.getY();
    }//GEN-LAST:event_backMousePressed

    private void backMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-setX, y-setY);
    }//GEN-LAST:event_backMouseDragged

    private void LIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LIMouseClicked
        launch.launchLinkedIn();
    }//GEN-LAST:event_LIMouseClicked

    private void GMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GMMouseClicked
        launch.launchGmail();
    }//GEN-LAST:event_GMMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GM;
    private javax.swing.JLabel LI;
    private javax.swing.JLabel back;
    // End of variables declaration//GEN-END:variables
public static void main(String args[]){
    java.awt.EventQueue.invokeLater(new Runnable(){
        public void run(){
            widgets dialog = new widgets(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter(){
                @Override
                public void windowClosing(java.awt.event.WindowEvent e){
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}
}